development:
  adapter: postgresql
  database: godchat
  username: <username>
  host: localhost
  port: 5432
  pool: 10

test:
  adapter: postgresql
  database: godchat_test
  username: <username>
  host: localhost
  port: 5432
  pool: 10
